'use client';
import { useState, useEffect } from 'react';
import { ArrowUpRight, Menu, X, Sun, Moon } from 'lucide-react';
import { editions } from './site-data';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { SiteLink } from './site-link';
const repos=[['indusagi-sdk','TypeScript SDK'],['induscode-ts','TypeScript Coding Agent'],['indusagi-rust','Rust SDK'],['induscode-rust','Rust Coding Agent'],['indusagi-python','Python SDK'],['induscode-python','Python Coding Agent']];
export function Header(){const[open,setOpen]=useState(false);const[light,setLight]=useState(false);useEffect(()=>{let v=false;try{v=localStorage.getItem('indus-theme')==='light'}catch{};setLight(v);document.documentElement.dataset.theme=v?'light':'dark'},[]);function theme(){const v=!light;setLight(v);document.documentElement.dataset.theme=v?'light':'dark';try{localStorage.setItem('indus-theme',v?'light':'dark')}catch{}}
return <header className="site-header"><SiteLink href="/" className="wordmark" aria-label="IndusAGI home"><img className="brand-image" src="/indusagi-logo.png" alt="IndusAGI" width="126" height="42"/></SiteLink><nav className={open?'main-nav is-open':'main-nav'} aria-label="Main navigation"><SiteLink href="/#benchmarks" onClick={()=>setOpen(false)}>Benchmarks</SiteLink><DropdownMenu><DropdownMenuTrigger className="nav-dropdown">Docs <span>⌄</span></DropdownMenuTrigger><DropdownMenuContent align="start" className="header-dropdown"><DropdownMenuLabel>Documentation</DropdownMenuLabel>{editions.map(e=><DropdownMenuItem asChild key={e.path}><SiteLink href={e.path} onClick={()=>setOpen(false)}><span className="repo-short">{e.short}</span><span>{e.lang}<small>{e.type}</small></span><ArrowUpRight size={15}/></SiteLink></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger className="nav-dropdown">GitHub <span>⌄</span></DropdownMenuTrigger><DropdownMenuContent align="start" className="header-dropdown"><DropdownMenuLabel>Repositories</DropdownMenuLabel>{repos.map(([repo,description])=><DropdownMenuItem asChild key={repo}><SiteLink href={'https://github.com/varunisrani/'+repo+'.git'} target="_blank" rel="noreferrer"><span>{repo}<small>{description}</small></span><ArrowUpRight size={15}/></SiteLink></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><SiteLink href="https://www.npmjs.com/package/indusagi" target="_blank" rel="noreferrer">npm <ArrowUpRight size={14}/></SiteLink><button className="mobile-theme" onClick={theme}>{light?<Moon size={17}/>:<Sun size={17}/>} {light?'Switch to dark theme':'Switch to white theme'}</button></nav><div className="header-actions"><button onClick={theme} className="icon-button" aria-label={light?'Switch to dark theme':'Switch to white theme'} title={light?'Switch to dark theme':'Switch to white theme'} aria-pressed={light}>{light?<Moon size={18}/>:<Sun size={18}/>}</button><SiteLink href="/docs" className="small-cta">Get started <ArrowUpRight size={16}/></SiteLink><button className="mobile-menu icon-button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>}
